<?php

namespace Aspyct\MongoMap;

require_once dirname(__FILE__) . '/../../../../src/Aspyct/MongoMap/ObjectInflator.php';

/**
 * Test class for ObjectInflator.
 * Generated by PHPUnit on 2012-07-11 at 17:00:42.
 */
class ObjectInflatorTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var ObjectInflator
     */
    protected $object;
    private $uniqueStringCount = 0;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new ObjectInflator;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Aspyct\MongoMap\ObjectInflator::inflate
     * @todo Implement testInflate().
     */
    public function testInflateFlatObject()
    {
        $publicWSet = $this->getUniqueString();
        $publicWoSet = $this->getUniqueString();
        $publicNonExisting = $this->getUniqueString();
        $protectedWSet = $this->getUniqueString();
        $protectedWoSet = $this->getUniqueString();
        $privateWSet = $this->getUniqueString();
        $privateWoSet = $this->getUniqueString();

        $dataArray = array(
            '__php_class' => 'Aspyct\MongoMap\ObjectInflatorTestATestClass',
            'publicWSet' => $publicWSet,
            'publicWoSet' => $publicWoSet,
            'publicNonExisting' => $publicNonExisting,
            'protectedWSet' => $protectedWSet,
            'protectedWoSet' => $protectedWoSet,
            'privateWSet' => $privateWSet,
            'privateWoSet' => $privateWoSet,
        );

        $expected = new ObjectInflatorTestATestClass();
        $expected->setPublicWSet($publicWSet);
        $expected->publicWoSet = $publicWoSet;
        $expected->setProtectedWSet($protectedWSet);
        $expected->defineProtectedWoSet($protectedWoSet);
        $expected->setPrivateWSet($privateWSet);
        $expected->definePrivateWoSet($privateWoSet);
        $expected->publicNonExisting = $publicNonExisting;


        $actual = $this->object->inflate($dataArray);

        $this->assertEquals($expected, $actual);
    }

    public function testInflateFlatObjectWithSubObjects()
    {
        $b1a = $this->getUniqueString();
        $b1b = $this->getUniqueString();
        $b2a = $this->getUniqueString();
        $b2b = $this->getUniqueString();

        $b1 = new ObjectInflatorTestBTestClass();
        $b1->setA($b1a);
        $b1->setB($b1b);
        $b2 = new ObjectInflatorTestBTestClass();
        $b2->setA($b2a);
        $b2->setB($b2b);

        $array1 = array(10, 55, 'a', 'F');
        $array2AsArray = array(array('__php_class' => 'Aspyct\MongoMap\ObjectInflatorTestBTestClass', 'a' => $b1a, 'b' => $b1b), array('__php_class' => 'Aspyct\MongoMap\ObjectInflatorTestBTestClass', 'a' => $b2a, 'b' => $b2b));
        $array2 = array($b1, $b2);

        $publicWSet = $array1;
        $publicWoSet = $this->getUniqueString();
        $publicNonExisting = $this->getUniqueString();
        $protectedWSet = $array2;
        $protectedWoSet = $this->getUniqueString();
        $privateWSet = $this->getUniqueString();
        $privateWoSet = $this->getUniqueString();

        $dataArray = array(
            '__php_class' => 'Aspyct\MongoMap\ObjectInflatorTestATestClass',
            'publicWSet' => $array1,
            'publicWoSet' => $publicWoSet,
            'publicNonExisting' => $publicNonExisting,
            'protectedWSet' => $array2AsArray,
            'protectedWoSet' => $protectedWoSet,
            'privateWSet' => $privateWSet,
            'privateWoSet' => $privateWoSet,
        );

        $expected = new ObjectInflatorTestATestClass();
        $expected->setPublicWSet($publicWSet);
        $expected->publicWoSet = $publicWoSet;
        $expected->setProtectedWSet($protectedWSet);
        $expected->defineProtectedWoSet($protectedWoSet);
        $expected->setPrivateWSet($privateWSet);
        $expected->definePrivateWoSet($privateWoSet);
        $expected->publicNonExisting = $publicNonExisting;


        $actual = $this->object->inflate($dataArray);

        $this->assertEquals($expected, $actual);
    }

    public function testInflateFlatArray()
    {
        $publicWSet = $this->getUniqueString();
        $publicWoSet = $this->getUniqueString();
        $publicNonExisting = $this->getUniqueString();
        $protectedWSet = $this->getUniqueString();
        $protectedWoSet = $this->getUniqueString();
        $privateWSet = $this->getUniqueString();
        $privateWoSet = $this->getUniqueString();

        $expected = array(
            'publicWSet' => $publicWSet,
            'publicWoSet' => $publicWoSet,
            'publicNonExisting' => $publicNonExisting,
            'protectedWSet' => $protectedWSet,
            'protectedWoSet' => $protectedWoSet,
            'privateWSet' => $privateWSet,
            'privateWoSet' => $privateWoSet,
        );

        $actual = $this->object->inflate($expected);

        $this->assertEquals($expected, $actual);
    }

    private function getUniqueString()
    {
        $this->uniqueStringCount++;
        return md5(time() + $this->uniqueStringCount);
    }

}

class ObjectInflatorTestATestClass
{

    public $publicWSet;
    public $publicWoSet;
    protected $protectedWSet;
    protected $protectedWoSet;
    private $privateWSet;
    private $privateWoSet;

    public function getPublicWSet()
    {
        return $this->publicWSet;
    }

    public function setPublicWSet($publicWSet)
    {
        $this->publicWSet = $publicWSet;
    }

    public function getProtectedWSet()
    {
        return $this->protectedWSet;
    }

    public function setProtectedWSet($protectedWSet)
    {
        $this->protectedWSet = $protectedWSet;
    }

    public function getPrivateWSet()
    {
        return $this->privateWSet;
    }

    public function setPrivateWSet($privateWSet)
    {
        $this->privateWSet = $privateWSet;
    }

    public function defineProtectedWoSet($protectedWoSet)
    {
        $this->protectedWoSet = $protectedWoSet;
    }

    public function definePrivateWoSet($privateWoSet)
    {
        $this->privateWoSet = $privateWoSet;
    }

}

class ObjectInflatorTestBTestClass
{

    private $a;
    private $b;

    public function getA()
    {
        return $this->a;
    }

    public function setA($a)
    {
        $this->a = $a;
    }

    public function getB()
    {
        return $this->b;
    }

    public function setB($b)
    {
        $this->b = $b;
    }

}